<a href="https://colab.research.google.com/github/oltrovato25/Python-Class-Trovato/blob/main/Trovato_HW01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HW 01

### Q1. Write a program to input your age and print whether you are more than or less than a billion seconds old.

In [ ]:
## Enter answer here.

billion_seconds_in_years = 1_000_000_000 / (60 * 60 * 24 * 365.25)

age = float(input("Enter your age in years: "))

if age * 365.25 * 24 * 60 * 60 > 1_000_000_000:
    print("You are more than a billion seconds old!")
else:
    print("You are less than a billion seconds old!")




Enter your age in years: 21
You are less than a billion seconds old!


### Q2. Create a list with 10 names. Print each name with a Good morning greeting with the name using a conditional loop.

For example

`name = ['Ashley', 'Brianna', 'Chetan', 'David', 'Eoin', 'Francois', 'Gemma', 'Hameed', 'Ishaan', 'Joanna']`

Outputs will be 'Good morning, Ashley', 'Good morning, Brianna', and so on.

In [ ]:
## Enter answer here.

names = ["Olivia", "Hannah", "Rachel", "Morgan", "Emilee", "Taylor", "Brooke", "Ella", "Lauren", "Nana"]

for name in names:
    print(f"Good morning, {name}!")


Good morning, Olivia!
Good morning, Hannah!
Good morning, Rachel!
Good morning, Morgan!
Good morning, Emilee!
Good morning, Taylor!
Good morning, Brooke!
Good morning, Ella!
Good morning, Lauren!
Good morning, Nana!


### Q3. Create a list of 15 numbers. Print only those numbers that are divisible by 2.

In [1]:
## Enter answer here.

numbers = [3, 8, 15, 22, 34, 47, 56, 63, 72, 89, 90, 101, 112, 135, 150]

for num in numbers:
    if num % 2 == 0:
        print(num)


8
22
34
56
72
90
112
150


### Q4. Print the squared numbers of a list containing at least 10 numbers with a mix of float, integer, and negative numbers. Use the longer method as well as list comprehension.

You can either generate your own list of 10 numbers or find use a random number generator.

In [2]:
## Enter answer here.

nums = [0,-1.25,15.86,-25]
method1_squares = []

for i in nums:
    method1_squares.append(i**2)

print(method1_squares)

## Now method 2

numbers = [3, -7, 2.5, -4.2, 10, 5.5, -8, 6, -3.3, 9]

for num in numbers:
    squared = num ** 2
    print(f"The square of {num} is {squared}")



[0, 1.5625, 251.53959999999998, 625]
The square of 3 is 9
The square of -7 is 49
The square of 2.5 is 6.25
The square of -4.2 is 17.64
The square of 10 is 100
The square of 5.5 is 30.25
The square of -8 is 64
The square of 6 is 36
The square of -3.3 is 10.889999999999999
The square of 9 is 81


### Q5. Write a program to print a year if it is a leap year.

In [3]:
year = int(input())

if year%4 == 0:
    print(year, "is a leap year")
else:
    print(year, "is not a leap year")

2003
2003 is not a leap year


### Q6. Use list comprensions to print all names in a list in upper case.

In [4]:

names = ["Olivia", "Rachel", "Hannah", "Emilee", "Morgan"]

uppercase_names = [name.upper() for name in names]

for name in uppercase_names:
    print(name)


OLIVIA
RACHEL
HANNAH
EMILEE
MORGAN


### Q7. Question on NUMPY arrays:

a. Create a numpy array called `original` with 100 random numbers. What is the largest number, smallest number, max, min, median, and standard deviation of your array? Print them.

HINT: use `np.random.uniform()`. Check online for the correct syntax. `np.random.rand(100)` will give you 100 random numbers of uniform distribution with mean 0 and standard deviation of 1, while we want a mix of larger numbers/integers.

b. Now create an array called `orig_sqrt` which contains the square roots of the numbers in the original array.

### Q8.  Converting 1D arrays into 2D arrays.

a. Convert your original array of 100 random numbers into a 2-dimensional array called `mat_array` with 20 rows and 5 columns. Print this array.

b. What is the mean of every column in `mat_array`?

c. What is the sum of every row? Create a list of 20 elements that contains the sum of every row in `mat_array`.

d. Create the transpose of `mat_array` and call it `transpose_array`. What are the dimensions of this array now? Again, find the mean of each column and the sum of each row.

### Q9. Array slicing:

a. create a new array which contains the 3rd-10th rows and all columns of `mat_array`. Print.

b. Print a new array which contains the the last 5 rows and the last 2 columns of `mat_array`. What is the dimension of this array?

c. Print a new array which contains the first 3 rows and last 10 columns of `transpose_array`.

In [7]:
# Write your answer here. Feel free to break your answer into different blocks of code rather than using just this one cell. Label your answer neatly.
import numpy as np



In [8]:
import numpy as np

original = np.random.uniform(low=1, high=1000, size=100)

largest_number = np.max(original)
smallest_number = np.min(original)
max_value = np.max(original)
min_value = np.min(original)
median_value = np.median(original)
std_deviation = np.std(original)

print(f"Largest number: {largest_number}")
print(f"Smallest number: {smallest_number}")
print(f"Max value: {max_value}")
print(f"Min value: {min_value}")
print(f"Median value: {median_value}")
print(f"Standard deviation: {std_deviation}")

orig_sqrt = np.sqrt(original)

print("\nSquare roots of the original array:")
print(orig_sqrt)


Largest number: 996.5929822919285
Smallest number: 15.313642795080508
Max value: 996.5929822919285
Min value: 15.313642795080508
Median value: 465.14890352061025
Standard deviation: 292.255858931869

Square roots of the original array:
[ 9.20923465 23.42871691  7.37486679 17.80358326 15.42870766 14.39206894
 28.51961221 10.8778343  12.22411135 31.26892947 15.74322888 29.86122572
 29.59459169 23.75769221 14.89224816 27.60282448 30.91664871 29.10034279
 20.05270931 31.25314828 19.58609525 23.58553012 19.09349195 11.91094779
  4.45475794 24.18480262 27.84252588 17.59957351 16.08515228  5.22633446
 22.62675155  9.98038238 20.30205208 27.35345651 10.48994376 31.56886096
 18.8485381  23.68189583 10.41698645 27.66348644 11.73375243  9.9052662
 21.83307449 23.32268219 29.31700913 21.76595719 21.36681807 30.30710736
 20.34263243 19.20902444 17.11188559 24.46116115 24.35998877 28.3141625
 27.81568343 13.56102971 23.57222484 30.83138848 27.0343554  16.91078681
 25.62152473 29.75661827 19.70817584

In [6]:
import numpy as np

original = np.random.uniform(low=1, high=1000, size=100)
mat_array = original.reshape(20, 5)

print("Original 2D Array (20 rows, 5 columns):")
print(mat_array)

column_means = np.mean(mat_array, axis=0)
print("\nMean of each column in mat_array:")
print(column_means)

row_sums = np.sum(mat_array, axis=1)
print("\nSum of every row in mat_array:")
print(row_sums)

transpose_array = mat_array.T

print(f"\nDimensions of the transpose array: {transpose_array.shape}")

transpose_column_means = np.mean(transpose_array, axis=0)
print("\nMean of each column in the transposed array:")
print(transpose_column_means)

transpose_row_sums = np.sum(transpose_array, axis=1)
print("\nSum of every row in the transposed array:")
print(transpose_row_sums)


Original 2D Array (20 rows, 5 columns):
[[675.53667425 305.86537554 617.95396828 928.39406465 837.99697053]
 [483.2082109  211.85050324 610.95254589  95.71764067 967.05208973]
 [151.32824601 319.69305016 577.54179786 365.60476021   3.7902352 ]
 [114.06854342 692.98886898 400.40815436  59.49525486 763.12274667]
 [482.19897982  56.61172859 481.49630825 294.35495464 700.47089547]
 [569.32228955 154.29528494 235.28383094 675.59335426 842.81286801]
 [308.25013927 508.43323156 835.06726018 973.37957661 978.21296674]
 [476.45362854 245.66960024 108.60363837 855.68037368 812.40817541]
 [217.21697441 875.88482618 279.17230674 793.89098081 206.97531656]
 [600.03525279 806.01973358 341.65611071 674.64857093 253.95234763]
 [ 87.79674866 991.67084063 434.787915   183.35405665 290.05601548]
 [752.76776709 398.56939325 261.97014982 700.16664358 971.80394938]
 [832.1188974  422.27682317 116.72854505 976.60692228 140.88674025]
 [975.68117482 177.17359472 885.6432155  523.75626728 721.7813317 ]
 [621.27

In [9]:
import numpy as np

original = np.random.uniform(low=1, high=1000, size=100)
mat_array = original.reshape(20, 5)
transpose_array = mat_array.T

sub_array_a = mat_array[2:10, :]
print("Sub-array containing rows 3 to 10 and all columns of mat_array:")
print(sub_array_a)

sub_array_b = mat_array[-5:, -2:]
print("\nSub-array containing the last 5 rows and last 2 columns of mat_array:")
print(sub_array_b)

print(f"Dimensions of the array in b: {sub_array_b.shape}")

sub_array_c = transpose_array[:3, -10:]
print("\nSub-array containing the first 3 rows and last 10 columns of transpose_array:")
print(sub_array_c)


Sub-array containing rows 3 to 10 and all columns of mat_array:
[[ 20.36183612 496.83348247 523.64180954 305.85231161 887.95708546]
 [266.53829781 414.21721896 637.21783933 866.75280149 924.20784135]
 [161.20985816 196.27392463 453.1835912   92.76137549 455.72432069]
 [880.59754979 610.74769904 174.83763738 810.44691351 671.36223577]
 [ 84.64997333 899.40475569 648.48334021 285.09235161 121.87174671]
 [ 89.13966564 803.99426513 390.57960438 715.5279213  903.64803136]
 [141.73842643 122.5855563  837.1618317  706.52630788 137.24527138]
 [ 60.00778441 847.44726673  77.44423139 300.96531763 269.48118619]]

Sub-array containing the last 5 rows and last 2 columns of mat_array:
[[201.43655673 351.29872224]
 [538.73574853 112.35862383]
 [702.0349111  371.50061732]
 [805.39451412 614.20407214]
 [905.5550983  684.55404401]]
Dimensions of the array in b: (5, 2)

Sub-array containing the first 3 rows and last 10 columns of transpose_array:
[[576.21133979 272.92341693  83.27686002 770.52373391 791.

### Q10. Assume you are inviting 15 friends to your party. You guest list has the following dietary preference.

`diet = ['vegetarian', 'pescetarian', 'vegetarian', 'omnivore', 'pescetarian', 'keto', 'keto', 'vegan', 'omnivore', 'omnivore', 'vegan', 'omnivore', 'keto, 'vegetarian', 'vegan']`

Their ages are as follows:

`age = [21, 20, 19, 25, 27, 18, 23, 25, 19, 22, 20, 20, 23, 21, 24]`

Create a list called `menu` which will contain 'veg. fried rice with whiskey' for vegans and vegetarians aged 21 and above,  'veg. fried rice with mocktail' for vegans and vegetarians aged below 21. Follow the same logic and assign fish and white wine to pescetarians of legal age (and fish with mocktail to those below 21). Keto and omnivore guests above 21 will have 'steak and red wine'. Complete the series with the appropriate drink for underage guests.

In [10]:
# Write your answer here.
import numpy as np

diet = ['vegetarian', 'pescetarian', 'vegetarian', 'omnivore', 'pescetarian', 'keto', 'keto', 'vegan', 'omnivore', 'omnivore', 'vegan', 'omnivore', 'keto', 'vegetarian', 'vegan']
age = [21, 20, 19, 25, 27, 18, 23, 25, 19, 22, 20, 20, 23, 21, 24]

menu = []

for i in range(len(diet)):
    if diet[i] == 'vegetarian' or diet[i] == 'vegan':
        if age[i] >= 21:
            menu.append('veg. fried rice with whiskey')
        else:
            menu.append('veg. fried rice with mocktail')
    elif diet[i] == 'pescetarian':
        if age[i] >= 21:
            menu.append('fish and white wine')
        else:
            menu.append('fish with mocktail')
    elif diet[i] == 'keto' or diet[i] == 'omnivore':
        if age[i] >= 21:
            menu.append('steak and red wine')
        else:
            menu.append('steak with mocktail')

print("Menu for your guests:")
for i, dish in enumerate(menu):
    print(f"Guest {i+1} (Age {age[i]}): {dish}")



Menu for your guests:
Guest 1 (Age 21): veg. fried rice with whiskey
Guest 2 (Age 20): fish with mocktail
Guest 3 (Age 19): veg. fried rice with mocktail
Guest 4 (Age 25): steak and red wine
Guest 5 (Age 27): fish and white wine
Guest 6 (Age 18): steak with mocktail
Guest 7 (Age 23): steak and red wine
Guest 8 (Age 25): veg. fried rice with whiskey
Guest 9 (Age 19): steak with mocktail
Guest 10 (Age 22): steak and red wine
Guest 11 (Age 20): veg. fried rice with mocktail
Guest 12 (Age 20): steak with mocktail
Guest 13 (Age 23): steak and red wine
Guest 14 (Age 21): veg. fried rice with whiskey
Guest 15 (Age 24): veg. fried rice with whiskey
